@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant "AccountManager" as AM
participant "Parser" as P
participant "UserInterface" as UI

User -> AM: processAddAccount(input)
AM -> AM: validateSyntax(input)
AM -> P: parseAddAccount(input)
activate P
P --> AM: parsedData
deactivate P
AM -> AM: addAccount(parsedData[0], parsedData[1])
AM -> UI: printAddAccountMessage(newAccount)
activate UI
UI --> AM: Display added account message
AM --> User : Confirmation message
deactivate UI
@enduml