@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant ":TransactionManager" as TM
participant ":Parser" as P
participant "UserInterface" as UI

User -> TM: processTransaction(input, account)
TM -> TM: validateSyntax(input)
TM -> P: parseUserInputToTransaction(input, account)
activate P
P -> P: checkCategory(transaction)

alt Category is null
    P -> UI: listCategories()
    activate UI
    UI --> User: Display category options
    User --> UI: categoryNum
    UI --> P: getCategoryNum()
    deactivate UI
end

P --> TM: transaction
deactivate P


TM -> TM: addTransaction(transaction)
TM -> UI: printAddMessage(transaction, account.balance)
activate UI
UI --> TM : Display added transaction message
TM --> User: Confirmation message
deactivate UI
@enduml