@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant ":TransactionManager" as TM
participant ":UserInterface" as UI
participant "LocalDate" as LD
participant ":AccountManager" as AM

User -> TM: processList()
TM -> UI: printListOptions()
activate UI
UI --> User: Display list options
deactivate UI
User -> TM: selectOption(option)
TM -> TM: determineAction(option)

alt 1: All Transactions
    TM -> TM: printTransactions()
    TM -> UI: printTransactions()
    activate UI
    UI --> TM: Display all transactions
    UI --> User: Confirmation message
    deactivate UI
else 2: Past Week Transactions
    TM -> LD: now()
    activate LD
    LD --> TM: today
    deactivate LD
    TM -> TM: calculateStartDate("week")
    TM -> TM: getPastTransactions(startDate)
    TM -> UI: printPastTransactions(transactions, "week")
    activate UI
    UI --> TM: Display past week transactions
    TM --> User: Confirmation message

    deactivate UI
else 3: Past Month Transactions
    TM -> LD: now()
    LD --> TM: today
    TM -> TM: calculateStartDate("month")
    TM -> TM: getPastTransactions(startDate)
    TM -> UI: printPastTransactions(transactions, "month")
    activate UI
    UI --> TM: Display past month transactions
    TM --> User: Confirmation message

    deactivate UI
else 4: Custom Date Transactions
    TM -> UI: getStartDate()
    activate UI
    UI --> TM: startDate
    deactivate UI
    TM -> UI: getEndDate()
    activate UI
    UI --> TM: endDate
    deactivate UI
    TM -> TM: parseDates(startDate, endDate)
    TM -> TM: getCustomDateTransactions(startDate, endDate)
    TM -> UI: printCustomDateTransactions(transactions)
    activate UI
    UI --> TM: Display custom date transactions
    TM --> User: Confirmation message

    deactivate UI
else 5: Account Transactions
    TM -> UI: printAccountList(accounts)
    activate UI
    UI --> User: Display account list
    deactivate UI
    TM -> UI: getSelectedAccountNumber(accounts)
    activate UI
    UI --> TM: accountNumber
    deactivate UI
    TM -> AM: getAccountByAccountNumber(accountNumber)
    activate AM
    AM --> TM: account
    deactivate AM
    TM -> TM: getAccountTransactions(transactions, accountNumber)
    TM -> UI: printAccountTransactions(accountTransactions, accountName, accountNumber)
    activate UI
    UI ---> TM: Display account transactions
    TM ---> User: Confirmation message

    deactivate UI
else 6: Category Transactions
    TM -> UI: listCategories()
    activate UI
    UI --> User: Display category list
    deactivate UI
    TM -> UI: getSelectedCategory()
    activate UI
    UI --> TM: categorySelected
    deactivate UI
    TM -> TM: fromNumber(category)
    TM -> TM: getCategoryName()
    TM -> TM: getCategoryTransactions(transactions, categorySelected)
    TM -> UI: printCategoryTransactions(categoryTransactions, categoryName)
    activate UI
    UI --> TM: Display category transactions
    TM --> User: Confirmation message

    deactivate UI
end
@enduml